import request from'@/utils/request';import type{ApiResponse,Examination,ExaminationAiReview,ExaminationItem,PageData,ReviewStats,StaffInfo}from'@/types';
export const login=(username:string,password:string)=>request.post<ApiResponse<string>>('/api/staff/login',{username,password,role:'lab'});
export const getInfo=()=>request.get<ApiResponse<StaffInfo>>('/api/staff/info');
export const changePassword=(oldPassword:string,newPassword:string)=>request.put<ApiResponse<string>>('/api/staff/change-password',{oldPassword,newPassword});
export const getExaminations=(status:string,page=1,size=10)=>request.get<ApiResponse<PageData<Examination>>>('/api/examination/lab/list',{params:{status,page,size}});
export const getExamination=(id:number)=>request.get<ApiResponse<Examination>>(`/api/examination/detail/${id}`);
export const updateResult=(data:{id:number;result:string;resultImages?:string})=>request.put<ApiResponse<string>>('/api/examination/update-result',null,{params:data});
export const getItems=(type?:string)=>request.get<ApiResponse<ExaminationItem[]>>('/api/examination/item/list',{params:{type}});
export const uploadFile=(file:File)=>{const form=new FormData();form.append('file',file);return request.post<ApiResponse<string>>('/api/file/upload',form,{headers:{'Content-Type':'multipart/form-data'}})};
export const getCriticalWarnings=(page=1,size=30)=>request.get<ApiResponse<PageData<any>>>('/api/examination/ai/critical-list',{params:{page,size}});
export const reviewExamination=(id:number)=>request.post<ApiResponse<any>>(`/api/examination/ai/review/${id}`);
export const getReviewList=(reviewResult?:string,page=1,size=10)=>request.get<ApiResponse<PageData<ExaminationAiReview>>>('/api/examination/ai/review-list',{params:{reviewResult,page,size}});
export const getManualReviews=(page=1,size=10)=>request.get<ApiResponse<PageData<ExaminationAiReview>>>('/api/examination/ai/manual-list',{params:{page,size}});
export const getReviewDetail=(id:number)=>request.get<ApiResponse<ExaminationAiReview>>(`/api/examination/ai/review-detail/${id}`);
export const manualConfirm=(id:number)=>request.post<ApiResponse<string>>(`/api/examination/ai/manual-confirm/${id}`);
export const rejectReview=(id:number,reason:string)=>request.post<ApiResponse<string>>(`/api/examination/ai/reject/${id}`,null,{params:{reason}});
export const getReviewStats=()=>request.get<ApiResponse<ReviewStats>>('/api/examination/ai/review-stats');
