<template>
  <div class="login-page">
    <section class="visual"><div class="visual-content"><div class="logo"><span><el-icon><DataAnalysis /></el-icon></span><div><strong>云脑诊疗</strong><small>NEUSOFT SMART CARE</small></div></div><div class="hero-copy"><div class="tag">智慧运营 · 安全管理</div><h1>让医疗管理，<br/>更清晰、更高效</h1><p>统一管理科室、医生与药品资源，以数据洞察支撑医院日常运营。</p></div><div class="features"><div><el-icon><CircleCheckFilled /></el-icon><span><b>全局数据概览</b><small>关键运营指标一目了然</small></span></div><div><el-icon><CircleCheckFilled /></el-icon><span><b>精细资源管理</b><small>科室、医生、药品统一维护</small></span></div><div><el-icon><CircleCheckFilled /></el-icon><span><b>角色权限保护</b><small>JWT 身份认证与接口鉴权</small></span></div></div></div></section>
    <section class="form-side"><div class="login-card"><div class="form-head"><span>ADMIN PORTAL</span><h2>欢迎登录管理中心</h2><p>请输入管理员账号，继续平台运营管理</p></div><el-form ref="formRef" :model="form" :rules="rules" label-position="top" @keyup.enter="submit"><el-form-item label="管理员账号" prop="username"><el-input v-model="form.username" size="large" :prefix-icon="User" placeholder="请输入管理员账号" clearable /></el-form-item><el-form-item label="登录密码" prop="password"><el-input v-model="form.password" size="large" :prefix-icon="Lock" type="password" show-password placeholder="请输入登录密码" /></el-form-item><div class="form-meta"><el-checkbox v-model="remember">记住账号</el-checkbox><span>账户问题请联系系统负责人</span></div><el-button class="login-btn" type="primary" size="large" :loading="loading" @click="submit">进入管理中心 <el-icon><ArrowRight /></el-icon></el-button></el-form><div class="security"><el-icon><Lock /></el-icon> 您的登录信息将通过安全连接传输</div></div></section>
  </div>
</template>

<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { useRouter } from 'vue-router'
import { ElMessage, type FormInstance, type FormRules } from 'element-plus'
import { User, Lock } from '@element-plus/icons-vue'
import { useAuthStore } from '@/stores/auth'

const router = useRouter(); const auth = useAuthStore(); const formRef = ref<FormInstance>(); const loading = ref(false); const remember = ref(true)
const form = reactive({ username: '', password: '' })
const rules: FormRules = { username: [{ required: true, message: '请输入管理员账号', trigger: 'blur' }], password: [{ required: true, message: '请输入登录密码', trigger: 'blur' }] }
onMounted(() => { form.username = localStorage.getItem('admin_username') || '' })
const submit = async () => { if (!await formRef.value?.validate().catch(() => false)) return; loading.value = true; try { await auth.login(form.username, form.password); if (remember.value) localStorage.setItem('admin_username', form.username); else localStorage.removeItem('admin_username'); ElMessage.success('登录成功，欢迎进入管理中心'); router.push('/dashboard') } finally { loading.value = false } }
</script>

<style scoped>
.login-page{min-height:100vh;display:grid;grid-template-columns:minmax(570px,1.1fr) minmax(470px,.9fr);background:#f7fafb}.visual{position:relative;overflow:hidden;padding:48px 58px;background:linear-gradient(145deg,#073b5c,#087d79 68%,#1da28e);color:#fff}.visual:before{content:"";position:absolute;width:550px;height:550px;right:-220px;top:-160px;border:1px solid rgba(255,255,255,.11);border-radius:50%;box-shadow:0 0 0 90px rgba(255,255,255,.025)}.visual-content{position:relative;z-index:1;display:flex;flex-direction:column;height:calc(100vh - 96px)}.logo{display:flex;align-items:center;gap:13px}.logo>span{width:48px;height:48px;display:flex;align-items:center;justify-content:center;border-radius:15px;background:linear-gradient(145deg,#4bd8c1,#effffb);color:#08656b;font-size:23px}.logo strong,.logo small{display:block}.logo strong{font-size:21px}.logo small{margin-top:3px;color:rgba(255,255,255,.55);font-size:8px;letter-spacing:1.7px}.hero-copy{margin:auto 0 36px;max-width:610px}.tag{display:inline-block;padding:7px 12px;border:1px solid rgba(255,255,255,.16);border-radius:20px;background:rgba(255,255,255,.08);font-size:11px;letter-spacing:1.5px}.hero-copy h1{margin:22px 0 18px;font-size:47px;line-height:1.25}.hero-copy p{max-width:530px;color:rgba(255,255,255,.68);font-size:14px;line-height:1.8}.features{display:grid;grid-template-columns:repeat(3,1fr);gap:13px}.features>div{display:flex;gap:9px;padding:15px 13px;border:1px solid rgba(255,255,255,.11);border-radius:15px;background:rgba(255,255,255,.07)}.features .el-icon{margin-top:2px;color:#67e3c9}.features b,.features small{display:block}.features b{font-size:11px}.features small{margin-top:4px;color:rgba(255,255,255,.48);font-size:9px}.form-side{display:flex;align-items:center;justify-content:center;padding:45px}.login-card{width:100%;max-width:420px}.form-head>span{color:#138f82;font-size:10px;font-weight:800;letter-spacing:2.3px}.form-head h2{margin:9px 0 8px;font-size:27px}.form-head p{margin-bottom:29px;color:#91a1a7;font-size:12px}.el-form-item{margin-bottom:20px}.el-form-item :deep(.el-form-item__label){padding-bottom:8px;color:#4c6872;font-size:12px;font-weight:650}.el-input :deep(.el-input__wrapper){min-height:47px;border-radius:12px;box-shadow:0 0 0 1px #dfe9eb inset}.form-meta{display:flex;justify-content:space-between;margin:-2px 0 20px;color:#98a7ac;font-size:10px}.login-btn{width:100%;height:48px;border:0;border-radius:12px;background:linear-gradient(135deg,#087f84,#16a393);box-shadow:0 9px 22px rgba(8,127,132,.2);font-weight:700}.security{display:flex;align-items:center;justify-content:center;gap:6px;margin-top:25px;color:#a5b1b5;font-size:9px}
</style>
